First version of actual collaboration service
Agar-OSS/agartex-collaboration pull request #4
Opened 2023-05-25 22:47 UTC by katzper01

What can I say. This is temporary.

2023-05-28 15:02 UTC, hubzie reviewed
Make i run under `/collaboration` and will be ok

2023-06-04 12:20 UTC, hubzie commented
I'm debugging this right now (containerized version is not working for some reason) and find out that:
* print is not visible in docker container logs -- use `logging` module
```python3
import loggin
logging.getLogger().setLevel(logging.INFO)
...
logging.info("message")
```
* by default there is no distinction between endpoints, so no action required to make it run under `/collaboration`

2023-06-04 12:26 UTC, hubzie requested changes
Change `print` to `logging.info` as in comment above and ready to merge

2023-06-04 12:26 UTC, hubzie commented on server.py
>  server = WebSocketServer('', 3400, SimpleChat)
```suggestion
server = WebSocketServer('0.0.0.0', 3400, SimpleChat)
```

2023-06-04 19:20 UTC, katzper01 commented on server.py
>  server = WebSocketServer('', 3400, SimpleChat)
done

2023-06-04 19:23 UTC, hubzie approved these changes

2023-06-04 19:23 UTC, merged